### PR TITLE
fix(runner): prioritize `chrome-ws-url` over `headless` flag

### LINKED ISSUE #1507: [BUG] Chrome WebSocket URL ignored when used with the headless flag
The Chrome WebSocket URL flag is ignored when combined with the headless flag, causing Katana to launch a new Chrome instance instead of connecting to an existing browser session. This breaks authenticated crawling via pre-authenticated Chrome sessions.

### PR DESCRIPTION
**Pull request by fail-open**
## Summary

Fixes a bug where the `-cwu` (Chrome WebSocket URL) flag is ignored when used together with `-headless` flag, making authenticated crawling via existing browser sessions impossible.

## Problem

When users follow the official documentation and run:
```bash
katana -headless -u https://tesla.com -cwu ws://127.0.0.1:9222/devtools/browser/XXX -no-incognito
```

**Expected:** Katana connects to existing browser session  
**Actual:** Katana launches a new Chrome instance and ignores the WebSocket URL

This occurs because the engine selection logic in `runner.go` checks the `-headless` flag before checking if a `ChromeWSUrl` is provided, causing the wrong engine to be selected.

## Solution

Prioritize `ChromeWSUrl` in the engine selection switch statement:

**Before:**
```go
switch {
case options.Headless:              // Checked first
    crawler, err = headless.New(crawlerOptions)
case options.HeadlessHybrid:
    crawler, err = hybrid.New(crawlerOptions)
default:
    crawler, err = standard.New(crawlerOptions)
}
```

**After:**
```go
switch {
case options.ChromeWSUrl != "":     // Check this first
    crawler, err = hybrid.New(crawlerOptions)
case options.Headless:
    crawler, err = headless.New(crawlerOptions)
case options.HeadlessHybrid:
    crawler, err = hybrid.New(crawlerOptions)
default:
    crawler, err = standard.New(crawlerOptions)
}
```

## Changes

1. **internal/runner/runner.go**: Prioritize ChromeWSUrl check in engine selection
2. **internal/runner/options.go**: Add warning when -headless is used with -cwu to inform users

### Before Fix
```bash
$ katana -headless -u https://example.com -cwu 'ws://localhost:9222/...' -no-incognito
# → Launches new browser (flash), ignores WebSocket URL
# → No new tabs in existing browser
```

### After Fix
```bash
$ katana -headless -u https://example.com -cwu 'ws://localhost:9222/...' -no-incognito
[WARN] Using -cwu with existing browser session. The -headless flag is ignored.
[INFO] Connecting to Chrome at: ws://localhost:9222/...
# → Connects to existing browser
# → New tabs appear in existing Chrome window
# → Has access to authenticated session
```

## Backward Compatibility

✅ Fully backward compatible - no breaking changes  
✅ Existing workflows continue to work as before  
✅ Makes documented example actually work  

## Related Issue

This makes the official documentation example work correctly. Currently, users must remove the `-headless` flag as a workaround, which contradicts the documentation.

### CODE REVIEW

File: internal/runner/options.go [hunk 1]
```diff
@@ -36,6 +36,14 @@ func validateOptions(options *types.Options) error {
...
 		return errkit.New("flags -hl (headless) and -hh (hybrid) are mutually exclusive")
 	}
+	
+	// Warn if -headless is used with -cwu (Chrome WebSocket URL)
+	// The ChromeWSUrl takes precedence and hybrid engine will be used
+	if options.Headless && options.ChromeWSUrl != "" {
+		gologger.Warning().Msgf("Using -cwu with existing browser session. The -headless flag is ignored.")
+		gologger.Info().Msgf("Connecting to Chrome at: %s", options.ChromeWSUrl)
+	}
+
```
Comment (dwisiswant0) [inline internal/runner/options.go]: I think these logs are fine to remove since the condition just falls through anyway.

```suggestion
```

**Review by dwisiswant0 — APPROVED** [review]
