### PR TITLE
Fix: Add option to disable unique content filter

### LINKED ISSUE #1350: Katana not reporting all 404 responses in OnResult callback
## Current Behavior

When crawling a website that returns multiple 404 (Not Found) responses, Katana's `OnResult` callback is not being invoked for most of these 404 responses. Even though Katana makes the HTTP requests and receives 404 status codes (verified through proxy logs), these responses are not passed to the `OnResult` callback.

## Expected Behavior

All HTTP responses, including 404 errors, should trigger the `OnResult` callback so that users can process and log them appropriately.

## Steps To Reproduce

1. Run Katana with the following command:
```bash
katana -debug -d 10 -kf -jc -jsl -j -sr -proxy http://127.0.0.1:8081 -do -dr -td -kf all -srd /tmp/katana_test -retry 2 -u https://httpbin.org -o /tmp/test | grep 'status_code":404'
```

2. Monitor proxy logs at `http://127.0.0.1:8081` to see actual HTTP requests being made

3. Observe that while the proxy shows dozens of 404 responses, only one or very few are captured in Katana's output

### Alternative reproduction using Go library:

```go
package main

import (
    "fmt"
    "github.com/projectdiscovery/katana/pkg/engine/standard"
    "github.com/projectdiscovery/katana/pkg/output"
    "github.com/projectdiscovery/katana/pkg/types"
)

func main() {
    options := &types.Options{
        MaxDepth:               10,
        StoreResponse:          true,
        Proxy:                  "http://127.0.0.1:8081",
        OnResult: func(result output.Result) {
            if result.Response != nil {
                fmt.Printf("Response: %s - Status: %d\n", result.Request.URL, result.Response.StatusCode)
            }
        },
    }
    
    crawlerOpts, _ := types.NewCrawlerOptions(options)
    crawler, _ := standard.New(crawlerOpts)
    crawler.Crawl("https://httpbin.org")
}
```

## Environment

- **Katana version**: v1.2.1
- **Go version**: 1.24.4
- **OS**: Darwin 22.6.0 (macOS)

### What I've discovered:
- The proxy logs show that Katana IS making requests to URLs that return 404
- The 404 responses are received by Katana (verified through proxy)
- However, the `OnResult` callback is not being invoked for most 404 responses
- This appears to be an internal filtering mechanism that prevents error responses from reaching the callback

### Why this is important:
- When building tools on top of Katana, we need to know about ALL responses, including errors
- 404 responses are valuable for security testing and mapping applications
- Without visibility into error responses, it's impossible to build accurate site maps or identify broken links

### Suspected cause:
It seems like there might be internal logic in Katana that filters out error responses before they reach the `OnResult` callback, possibly as an optimization. However, this prevents legitimate use cases where error responses need to be processed.

## Possible Solution

Consider adding an option like `IncludeErrorResponses` or `ReportAllResponses` that ensures all HTTP responses (including 4xx and 5xx) are passed to the `OnResult` callback.

```go
options := &types.Options{
    IncludeErrorResponses: true, // New option
    OnResult: func(result output.Result) {
        // Now receives ALL responses, including 404s
    },
}

### PR DESCRIPTION
**Pull request by nirohfeld**
## Description

This PR addresses issue #1350 where 404 responses (and other responses with duplicate content) are being filtered out before reaching the `OnResult` callback.

## Root Cause

Katana uses a unique content filter (`UniqueFilter.UniqueContent`) in the crawling process to deduplicate responses with identical content. While this is useful for avoiding duplicate processing, it causes issues when users need to see all responses, including those with duplicate content (like multiple 404 pages).

The filtering happens in `/pkg/engine/standard/crawl.go` at lines 79-83, where responses with duplicate content return an empty `navigation.Response{}` which doesn't trigger the `OnResult` callback.

## Solution

Added a new command-line flag `--disable-unique-filter` / `-duf` that allows users to disable the duplicate content filtering entirely. This ensures all responses reach the `OnResult` callback regardless of content duplication.

### Changes Made:

1. Added `DisableUniqueFilter bool` field to `pkg/types/options.go`
2. Added command-line flag `-duf, --disable-unique-filter` in `cmd/katana/main.go`
3. Modified `pkg/engine/standard/crawl.go` to skip unique content filtering when the option is enabled
4. Added integration test to verify the fix works correctly

## Testing

Created integration tests to verify the fix works correctly:
- Test 1: Default behavior (unique filter enabled) - Only first 404 response is captured
- Test 2: With `-duf` flag - All 404 responses are captured

## Usage Example

```bash
# Default behavior - duplicate 404 pages are filtered
katana -u https://example.com

# With fix - all responses including duplicate 404s are captured
katana -u https://example.com -duf
```

## Breaking Changes

None. This is a backward-compatible addition with the default behavior unchanged.

## Related Issues

Fixes #1350

## Summary by CodeRabbit

* **New Features**
  * Added a command-line flag to disable duplicate content filtering, allowing all responses (including duplicates) to be reported.
* **Bug Fixes**
  * Improved handling of duplicate 404 responses when the unique filter is disabled.
* **Tests**
  * Introduced integration tests to verify the behavior with and without duplicate content filtering enabled.

### CODE REVIEW

File: pkg/types/options.go [hunk 1]
```diff
@@ -170,6 +170,8 @@ type Options struct {
 	DisableRedirects bool
 	// PathClimb enables path expansion (auto crawl discovered paths)
 	PathClimb bool
+	// DisableUniqueFilter disables duplicate content filtering
+	DisableUniqueFilter bool
```
Comment (dogancanbakir) [inline pkg/types/options.go:174]: We can use more [positive](https://refactoring.com/catalog/removeDoubleNegative.html) naming here -minor
